### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by JessyRiordan** [JessyRiordan/BeautyMark#1]
# BeautyMark Plan
### User Stories
- [ ] A beauty customer can log into BeautyMark to see their account details with their virtual beauty products. #2 
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] A beauty customer can access beauty categories so that they can view the list products they own in that category. #3
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] A beauty customer can input new beauty products (items) so that they can keep track of the beauty products they own. #4
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] _**Stretch**_ A beauty customer can upload a picture of a beauty product so that they can have a visual representation. #5
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] _**Stretch**_ A beauty customer can rate a beauty product (item) so that they can later decide to repurchase. #6
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] A beauty customer can delete a beauty product so that they know they do not own it anymore. #7
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] _**Stretch**_A beauty customer can share a beauty product (item) via email so that they can recommend products to other beauty lovers. #8 
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] _**Stretch**_A beauty customer can share a beauty product (item) via twitter so that they can recommend products to other beauty lovers. #9 
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] _**Stretch**_A beauty customer can share a beauty product (item) via Facebook so that they can recommend products to other beauty lovers. #10 
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
- [ ] _**Stretch**_A beauty customer can click on links to beauty websites (Sephora, Ulta, etc.) so that they can repurchase products they have used up. #11
  - [x] Created Issue
  - [x] Created Milestone
  - [x] Linked Issues and Milestone
  - [x] Added basic information about User Story in the issue
  - [ ] Added features for the issue - linked
  - [ ] Completed User Story
### Deadlines
- [x] Wednesday, July 8th - Planning #13 
- [ ] Friday, July 10th - Yak Shaving (0.0.0) #12 
- [ ] Monday, July 13th - First Features
- [ ] Wednesday, July 15th - First Release (0.1.0)
- [ ] Friday, July 17th - Mostly MVP (1.0.0)
- [ ] Monday, July 20th - Final Release (1.Y.0)
- [ ] Wednesday, July 22nd - Code Freeze (1.Y.Z)
