### ISSUE TITLE
Plan - Tuesday (7/7) - Making Plans

### ISSUE THREAD

**Issue by JessyRiordan** [JessyRiordan/BeautyMark#13]
- [x] Create repo
- [x] Create wiki
  - [x] home page - info from presentation
  - [x] User Stories
  - [x] Sketches
- [x] Create Issue for each User Story
  - [x] A beauty customer can log into BeautyMark to see their account details with their virtual beauty products. #2 
  - [x] A beauty customer can access beauty categories so that they can view the list products they own in that category. #3
  - [x] A beauty customer can input new beauty products (items) so that they can keep track of the beauty products they own. #4
  - [x] _**Stretch**_ A beauty customer can upload a picture of a beauty product so that they can have a visual representation. #5
  - [x] _**Stretch**_ A beauty customer can rate a beauty product (item) so that they can later decide to repurchase. #6
  - [x] A beauty customer can delete a beauty product so that they know they do not own it anymore. #7
  - [x] _**Stretch**_A beauty customer can share a beauty product (item) via email so that they can recommend products to other beauty lovers. #8 
  - [x] _**Stretch**_A beauty customer can share a beauty product (item) via twitter so that they can recommend products to other beauty lovers. #9 
  - [x] _**Stretch**_A beauty customer can share a beauty product (item) via Facebook so that they can recommend products to other beauty lovers. #10 
  - [x] _**Stretch**_A beauty customer can click on links to beauty websites (Sephora, Ulta, etc.) so that they can repurchase products they have used up. #11
- [x] Create Milestones for each deadline
  - [x] Wednesday, July 8th - Planning
  - [x] Friday, July 10th - Yak Shaving (0.0.0)
  - [x] Monday, July 13th - First Features
  - [x] Wednesday, July 15th - First Release (0.1.0)
  - [x] Friday, July 17th - Mostly MVP (1.0.0)
  - [x] Monday, July 20th - Final Release (1.Y.0)
  - [x] Wednesday, July 22nd - Code Freeze (1.Y.Z)
- [x] Create Milestone for each User Story
  - [x] A beauty customer can log into BeautyMark to see their account details with their virtual beauty products. #2 
  - [x] A beauty customer can access beauty categories so that they can view the list products they own in that category. #3
  - [x] A beauty customer can input new beauty products (items) so that they can keep track of the beauty products they own. #4
  - [x] _**Stretch**_ A beauty customer can upload a picture of a beauty product so that they can have a visual representation. #5
  - [x] _**Stretch**_ A beauty customer can rate a beauty product (item) so that they can later decide to repurchase. #6
  - [x] A beauty customer can delete a beauty product so that they know they do not own it anymore. #7
  - [x] _**Stretch**_A beauty customer can share a beauty product (item) via email so that they can recommend products to other beauty lovers. #8 
  - [x] _**Stretch**_A beauty customer can share a beauty product (item) via twitter so that they can recommend products to other beauty lovers. #9 
  - [x] _**Stretch**_A beauty customer can share a beauty product (item) via Facebook so that they can recommend products to other beauty lovers. #10 
  - [x] _**Stretch**_A beauty customer can click on links to beauty websites (Sephora, Ulta, etc.) so that they can repurchase products they have used up. #11
